version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/Hunter-commits/kernel_mido.git --single-branch -b oc mido
           cd mido
           wget https://raw.githubusercontent.com/Hunter-commits/ci/main/build.sh
           bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
